/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author wil-laptop
 */
public class RegistrarHC extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrarHC
     */
    public RegistrarHC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDNI = new app.bolivia.swing.JCTextField();
        txt_NombreApll = new app.bolivia.swing.JCTextField();
        txt_Direccion = new app.bolivia.swing.JCTextField();
        jPanel3 = new javax.swing.JPanel();
        Check_Masculino = new RSMaterialComponent.RSCheckBoxMaterial();
        Check_Femenino = new RSMaterialComponent.RSCheckBoxMaterial();
        ButtonBuscarP = new rojeru_san.RSButtonRiple();
        ButtonRegistrarHC = new rojeru_san.RSButtonRiple();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        PanelConsume = new javax.swing.JPanel();
        txtalcohol = new app.bolivia.swing.JCTextField();
        txttabaco = new app.bolivia.swing.JCTextField();
        txtinfuciones = new app.bolivia.swing.JCTextField();
        txtdrogas = new app.bolivia.swing.JCTextField();
        Check_Alcoholsi = new RSMaterialComponent.RSCheckBoxMaterial();
        Check_Alcoholno = new RSMaterialComponent.RSCheckBoxMaterial();
        jLabel12 = new javax.swing.JLabel();
        Check_Tabacosi = new RSMaterialComponent.RSCheckBoxMaterial();
        Check_Tabacono = new RSMaterialComponent.RSCheckBoxMaterial();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Check_Drogassi = new RSMaterialComponent.RSCheckBoxMaterial();
        Check_Drogasno = new RSMaterialComponent.RSCheckBoxMaterial();
        jLabel15 = new javax.swing.JLabel();
        Check_infucionessi = new RSMaterialComponent.RSCheckBoxMaterial();
        Check_infucionesno = new RSMaterialComponent.RSCheckBoxMaterial();
        jScrollPane3 = new javax.swing.JScrollPane();
        PanelMas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_alimentacion = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_diuresis = new app.bolivia.swing.JCTextField();
        txt_catarsis = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_sueño = new app.bolivia.swing.JCTextField();
        txt_enfermedad = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_codigo = new javax.swing.JLabel();
        Foto = new rojerusan.RSLabelImage();

        setClosable(true);
        setIconifiable(true);
        setTitle("REGISTRAR HISTORIAL CLÍNICO");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR HISTORIAL CLÍNICO");

        txtDNI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDNI.setEnabled(false);
        txtDNI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_NombreApll.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NombreApll.setEnabled(false);
        txt_NombreApll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_Direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Direccion.setEnabled(false);
        txt_Direccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));

        Check_Masculino.setText("MASCULINO");
        Check_Masculino.setEnabled(false);
        Check_Masculino.setIsEffectRipple(false);
        Check_Masculino.setThemeTooltip(necesario.Global.THEMETOOLTIP.LIGHT);

        Check_Femenino.setText("FEMENINO");
        Check_Femenino.setEnabled(false);
        Check_Femenino.setIsEffectRipple(false);
        Check_Femenino.setThemeTooltip(necesario.Global.THEMETOOLTIP.LIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Check_Masculino, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Check_Femenino, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Check_Masculino, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Check_Femenino, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonBuscarP.setBorder(null);
        ButtonBuscarP.setText("BUSCAR PACIENTE");
        ButtonBuscarP.setToolTipText("Cama de hospitalización");
        ButtonBuscarP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ButtonRegistrarHC.setBorder(null);
        ButtonRegistrarHC.setText("REGISTRAR H.C.");
        ButtonRegistrarHC.setToolTipText("Click para guardar paciente");
        ButtonRegistrarHC.setEnabled(false);

        jLabel2.setText("DNI:");

        jLabel3.setText("NOMBRES Y APELLIDOS:");

        jLabel4.setText("DIRECCIÓN:");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("ANAMNESIS"));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        PanelConsume.setBackground(new java.awt.Color(255, 255, 255));

        txtalcohol.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtalcohol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtalcohol.setNextFocusableComponent(Check_Tabacosi);
        txtalcohol.setPlaceholder("Descripción:");

        txttabaco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttabaco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttabaco.setNextFocusableComponent(Check_Drogassi);
        txttabaco.setPlaceholder("Descripción:");

        txtinfuciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtinfuciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtinfuciones.setNextFocusableComponent(txt_alimentacion);
        txtinfuciones.setPlaceholder("Descripción:");

        txtdrogas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdrogas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdrogas.setNextFocusableComponent(Check_infucionessi);
        txtdrogas.setPlaceholder("Descripción:");

        Check_Alcoholsi.setText("SÍ");
        Check_Alcoholsi.setIsEffectRipple(false);
        Check_Alcoholsi.setNextFocusableComponent(Check_Alcoholno);
        Check_Alcoholsi.setThemeTooltip(necesario.Global.THEMETOOLTIP.LIGHT);

        Check_Alcoholno.setText("NO");
        Check_Alcoholno.setIsEffectRipple(false);
        Check_Alcoholno.setNextFocusableComponent(txtalcohol);
        Check_Alcoholno.setThemeTooltip(necesario.Global.THEMETOOLTIP.LIGHT);

        jLabel12.setText("Cosume Alcohol");

        Check_Tabacosi.setText("SÍ");
        Check_Tabacosi.setToolTipText("");
        Check_Tabacosi.setIsEffectRipple(false);
        Check_Tabacosi.setNextFocusableComponent(Check_Tabacono);
        Check_Tabacosi.setThemeTooltip(necesario.Global.THEMETOOLTIP.LIGHT);

        Check_Tabacono.setText("NO");
        Check_Tabacono.setIsEffectRipple(false);
        Check_Tabacono.setNextFocusableComponent(txttabaco);
        Check_Tabacono.setThemeTooltip(necesario.Global.THEMETOOLTIP.LIGHT);

        jLabel13.setText("Cosume Tabaco");

        jLabel14.setText("Cosume Drogas");

        Check_Drogassi.setText("SÍ");
        Check_Drogassi.setToolTipText("");
        Check_Drogassi.setIsEffectRipple(false);
        Check_Drogassi.setNextFocusableComponent(Check_Drogasno);
        Check_Drogassi.setThemeTooltip(necesario.Global.THEMETOOLTIP.LIGHT);

        Check_Drogasno.setText("NO");
        Check_Drogasno.setIsEffectRipple(false);
        Check_Drogasno.setNextFocusableComponent(txtdrogas);
        Check_Drogasno.setThemeTooltip(necesario.Global.THEMETOOLTIP.LIGHT);

        jLabel15.setText("Cosume Infusiones");

        Check_infucionessi.setText("SÍ");
        Check_infucionessi.setToolTipText("");
        Check_infucionessi.setIsEffectRipple(false);
        Check_infucionessi.setNextFocusableComponent(Check_infucionesno);
        Check_infucionessi.setThemeTooltip(necesario.Global.THEMETOOLTIP.LIGHT);

        Check_infucionesno.setText("NO");
        Check_infucionesno.setIsEffectRipple(false);
        Check_infucionesno.setNextFocusableComponent(txtinfuciones);
        Check_infucionesno.setThemeTooltip(necesario.Global.THEMETOOLTIP.LIGHT);

        javax.swing.GroupLayout PanelConsumeLayout = new javax.swing.GroupLayout(PanelConsume);
        PanelConsume.setLayout(PanelConsumeLayout);
        PanelConsumeLayout.setHorizontalGroup(
            PanelConsumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsumeLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtdrogas, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(PanelConsumeLayout.createSequentialGroup()
                .addGroup(PanelConsumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelConsumeLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(PanelConsumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Check_Alcoholsi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Check_Tabacosi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Check_Drogassi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Check_infucionessi, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelConsumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Check_Alcoholno, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Check_Tabacono, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Check_Drogasno, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Check_infucionesno, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelConsumeLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelConsumeLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelConsumeLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelConsumeLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelConsumeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtalcohol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelConsumeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txttabaco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelConsumeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtinfuciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelConsumeLayout.setVerticalGroup(
            PanelConsumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsumeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelConsumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Check_Alcoholsi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Check_Alcoholno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtalcohol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelConsumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Check_Tabacosi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Check_Tabacono, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttabaco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelConsumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Check_Drogassi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Check_Drogasno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdrogas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelConsumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Check_infucionessi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Check_infucionesno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtinfuciones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(PanelConsume);

        jTabbedPane1.addTab("Consumibles", jScrollPane2);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        PanelMas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Qué tipo de alimentación consume:");

        txt_alimentacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_alimentacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_alimentacion.setNextFocusableComponent(txt_diuresis);
        txt_alimentacion.setPlaceholder("Escribir aquí...");

        jLabel6.setText("Diuresis:");

        txt_diuresis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_diuresis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_diuresis.setNextFocusableComponent(txt_catarsis);
        txt_diuresis.setPlaceholder("Escribir aquí...");

        txt_catarsis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_catarsis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_catarsis.setNextFocusableComponent(txt_sueño);
        txt_catarsis.setPlaceholder("Escribir aquí...");

        jLabel7.setText("Catarsis:");

        jLabel8.setText("Sueño:");

        txt_sueño.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_sueño.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_sueño.setNextFocusableComponent(txt_enfermedad);
        txt_sueño.setPlaceholder("Escribir aquí...");

        txt_enfermedad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_enfermedad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_enfermedad.setNextFocusableComponent(ButtonRegistrarHC);
        txt_enfermedad.setPlaceholder("Escribir aquí...");

        jLabel9.setText("Enfermedad:");

        javax.swing.GroupLayout PanelMasLayout = new javax.swing.GroupLayout(PanelMas);
        PanelMas.setLayout(PanelMasLayout);
        PanelMasLayout.setHorizontalGroup(
            PanelMasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_alimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_diuresis, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_catarsis, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txt_sueño, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_enfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMasLayout.setVerticalGroup(
            PanelMasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_alimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_diuresis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_catarsis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_sueño, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_enfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(PanelMas);

        jTabbedPane1.addTab("Más", jScrollPane3);

        jLabel10.setText("Código de HC.");

        lbl_fecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Fecha de creación");

        lbl_codigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos2/descarga.png"))); // NOI18N
        Foto.setToolTipText("Foto menor a 1MB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(lbl_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_NombreApll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonRegistrarHC, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addComponent(Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_NombreApll, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonRegistrarHC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojeru_san.RSButtonRiple ButtonBuscarP;
    public rojeru_san.RSButtonRiple ButtonRegistrarHC;
    public RSMaterialComponent.RSCheckBoxMaterial Check_Alcoholno;
    public RSMaterialComponent.RSCheckBoxMaterial Check_Alcoholsi;
    public RSMaterialComponent.RSCheckBoxMaterial Check_Drogasno;
    public RSMaterialComponent.RSCheckBoxMaterial Check_Drogassi;
    public RSMaterialComponent.RSCheckBoxMaterial Check_Femenino;
    public RSMaterialComponent.RSCheckBoxMaterial Check_Masculino;
    public RSMaterialComponent.RSCheckBoxMaterial Check_Tabacono;
    public RSMaterialComponent.RSCheckBoxMaterial Check_Tabacosi;
    public RSMaterialComponent.RSCheckBoxMaterial Check_infucionesno;
    public RSMaterialComponent.RSCheckBoxMaterial Check_infucionessi;
    public rojerusan.RSLabelImage Foto;
    public javax.swing.JPanel PanelConsume;
    public javax.swing.JPanel PanelMas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel lbl_codigo;
    public javax.swing.JLabel lbl_fecha;
    public app.bolivia.swing.JCTextField txtDNI;
    public app.bolivia.swing.JCTextField txt_Direccion;
    public app.bolivia.swing.JCTextField txt_NombreApll;
    public app.bolivia.swing.JCTextField txt_alimentacion;
    public app.bolivia.swing.JCTextField txt_catarsis;
    public app.bolivia.swing.JCTextField txt_diuresis;
    public app.bolivia.swing.JCTextField txt_enfermedad;
    public app.bolivia.swing.JCTextField txt_sueño;
    public app.bolivia.swing.JCTextField txtalcohol;
    public app.bolivia.swing.JCTextField txtdrogas;
    public app.bolivia.swing.JCTextField txtinfuciones;
    public app.bolivia.swing.JCTextField txttabaco;
    // End of variables declaration//GEN-END:variables
}
